# Generated by Django 4.1.5 on 2023-12-07 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralUserProflie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('phoneNumber', models.CharField(default='+263 xxx xxx xxxx', max_length=25)),
                ('profile_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='static/profileImages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
