# Generated by Django 4.1.5 on 2024-01-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_worklog_operators'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
