# Generated by Django 4.1.5 on 2024-01-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_equipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieselpurchase',
            name='litres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dieselpurchase',
            name='receiptNumber',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
