# Generated by Django 4.1.5 on 2024-01-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_dieselpurchase_litres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='phoneNumber',
            field=models.CharField(default='+263xxxxxxxxx', max_length=15),
        ),
    ]
