# Generated by Django 4.1.5 on 2024-01-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_worklog_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('openingHr', models.DecimalField(decimal_places=2, max_digits=20)),
                ('closingHr', models.DecimalField(decimal_places=2, max_digits=20)),
                ('depart_from', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvlog_machine_name', to='system.equipment')),
            ],
        ),
    ]
