# Generated by Django 4.1.5 on 2024-01-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_movelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
