# Generated by Django 4.1.5 on 2024-01-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_machine', models.CharField(default='loader', max_length=255)),
                ('template_name', models.CharField(default='Loading Bay', max_length=255)),
                ('location', models.CharField(default='HQ', max_length=255)),
                ('contacts', models.CharField(default='02 xxx-xxxx / 02 xxx-xxxx', max_length=255)),
            ],
        ),
    ]
